name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: install-dependencies
        run: |
          yarn install --frozen-lockfile
        
      - name: Build App
        id: build-app
        run: |
          yarn run build

